name: Word document review

on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pull-requests: write
  pages: write
  id-token: write

jobs:
  review:
    uses: JSv4/docx-actions/.github/workflows/review.yml@v1
